#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("_329230924finalProject.Resource", IsApplication=true)]

namespace _329230924finalProject
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020001
			public const int choback = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int generic = 2130837506;
			
			// aapt resource value: 0x7F020000
			public const int LIKED = 2130837504;
			
			// aapt resource value: 0x7F020003
			public const int recent = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030028
			public const int action_login = 2130903080;
			
			// aapt resource value: 0x7F030027
			public const int action_log_out = 2130903079;
			
			// aapt resource value: 0x7F030029
			public const int action_update = 2130903081;
			
			// aapt resource value: 0x7F030004
			public const int ForgotconfirmPasswordContentET = 2130903044;
			
			// aapt resource value: 0x7F030000
			public const int ForgotEMailContentET = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ForgotPassContentET = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ForgotResetBTN = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ForgotUNameContentET = 2130903043;
			
			// aapt resource value: 0x7F030005
			public const int HomeLO = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int LoginIForgorBTN = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int LoginLogInBTN = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int LoginPasswordContentET = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int LoginRememberMeCB = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int LoginShowPassCB = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int LoginUNameContentET = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int MainCAGBTN = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int MainLoginBTN = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int MainRegisterBTN = 2130903054;
			
			// aapt resource value: 0x7F030010
			public const int PFPcaptureBTN = 2130903056;
			
			// aapt resource value: 0x7F03000F
			public const int PFPConfrirmBTN = 2130903055;
			
			// aapt resource value: 0x7F030011
			public const int PFPuploadPhotoBTN = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int RegisterConPassContentET = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int RegisterDateSelectionBTN = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int RegisterEmailContentET = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int RegisterFNameContentET = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int RegisterLNameContentET = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int RegisterPassContentET = 2130903063;
			
			// aapt resource value: 0x7F03001B
			public const int RegisterpfpSelectionBTN = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int RegisterpfpviewIV = 2130903068;
			
			// aapt resource value: 0x7F030018
			public const int RegisterPhoneContentET = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int RegisterRegistrationBTN = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int RegisterUNameContentET = 2130903066;
			
			// aapt resource value: 0x7F03002A
			public const int thisImageView = 2130903082;
			
			// aapt resource value: 0x7F03001D
			public const int UpdateConPassContentET = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int UpdateDateSelectionBTN = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int UpdateEmailContentET = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int UpdateFNameContentET = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int UpdateLNameContentET = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int UpdatePassContentET = 2130903074;
			
			// aapt resource value: 0x7F030025
			public const int UpdatepfpSelectionBTN = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int UpdatepfpviewIV = 2130903078;
			
			// aapt resource value: 0x7F030023
			public const int UpdatePhoneContentET = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int UpdateUNameContentTV = 2130903076;
			
			// aapt resource value: 0x7F03002B
			public const int updateUpdatingBTN = 2130903083;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040006
			public const int activity_main = 2130968582;
			
			// aapt resource value: 0x7F040000
			public const int ForgotLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int HomeLayout = 2130968577;
			
			// aapt resource value: 0x7F040007
			public const int layoutnotesMenu = 2130968583;
			
			// aapt resource value: 0x7F040002
			public const int LoginLayout = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int PFPLayout = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int RegisterLayout = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int UpdateLayout = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int menuchophone = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
